name: Terraform Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  terraform:
    name: Deploy Terraform to AWS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check Dir
        run: ls -la

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-west-1  

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Validate
        run: terraform validate
        working-directory: terraform

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: terraform

      - name: Check Dir
        run: ls -la

      - name: Check Dir
        run: ls -la terraform

      - name: Convert plan output to json file
        run: terraform show -json tfplan > tfplan.json
        working-directory: terraform
      
      - name: Setup Infracost
        uses: infracost/actions/setup@v3
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}

      - name: Check Dir
        run: ls -la

      - name: Check Dir
        run: ls -la terraform

      - name: Generate Infracost cost estimate baseline
        run: |
          infracost breakdown --path=terraform/tfplan.json \
                              --format=json \
                              --log-level=info \
                              --out-file=/tmp/infracost-base.json
          cat /tmp/infracost-base.json

      - name: Generate Infracost diff
        run: |
          infracost diff --path=terraform/tfplan.json \
                          --format=json \
                          --compare-to=/tmp/infracost-base.json \
                          --log-level=info \
                          --out-file=/tmp/infracost.json
          cat /tmp/infracost.json

      - name: Post Infracost comment
        run: |
            infracost comment github --path=/tmp/infracost.json \
                                     --repo=$GITHUB_REPOSITORY \
                                     --github-token=${{ github.token }} \
                                     --pull-request=${{ github.event.pull_request.number }} \
                                     --behavior=delete-and-new

      - name: Terraform Apply
        if: github.event_name == 'push'
        run: terraform apply -auto-approve
        working-directory: terraform
